# Generated by Django 5.1 on 2025-12-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bluecard",
            field=models.BooleanField(default=False),
        ),
    ]
