# Generated by Django 5.1 on 2025-11-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="image",
            field=models.URLField(null=True),
        ),
    ]
