# Generated by Django 5.1 on 2025-12-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0005_remove_children_fundraiser"),
        ("fundraisers", "0002_alter_fundraiser_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraiser",
            name="child",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_fundraisers",
                to="children.children",
            ),
            preserve_default=False,
        ),
    ]
