# Generated by Django 5.1 on 2025-12-09 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0003_fundraiser_child"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundraiser",
            name="child",
        ),
        migrations.AddField(
            model_name="pledge",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
