# Generated by Django 5.1 on 2025-12-13 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0004_remove_fundraiser_child_pledge_date_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pledge",
            name="hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="pledge",
            name="pledge_type",
            field=models.CharField(
                choices=[("money", "Money"), ("time", "Time")],
                default="money",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="comment",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="supporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pledges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
