# Generated by Django 5.1 on 2025-12-02 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Children",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("DOB", models.DateField()),
                ("description", models.TextField()),
                ("SpecialHelp", models.BooleanField()),
                ("Specify", models.TextField()),
                ("image", models.URLField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_child",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
