# Generated by Django 5.1 on 2025-12-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="children",
            old_name="user",
            new_name="fundraiser",
        ),
    ]
