# Generated by Django 5.1 on 2025-12-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0002_rename_user_children_fundraiser"),
        ("fundraisers", "0002_alter_fundraiser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="children",
            name="fundraiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_child",
                to="fundraisers.fundraiser",
            ),
        ),
    ]
