# Generated by Django 5.1 on 2025-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0003_alter_children_fundraiser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="children",
            name="Specify",
            field=models.TextField(null=True),
        ),
    ]
