# Generated by Django 5.1 on 2025-12-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0004_alter_children_specify"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="children",
            name="fundraiser",
        ),
    ]
