# Generated by Django 5.1 on 2025-12-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0005_remove_children_fundraiser"),
        ("fundraisers", "0004_remove_fundraiser_child_pledge_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="children",
            name="fundraisers",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_fundraisers",
                to="fundraisers.fundraiser",
            ),
            preserve_default=False,
        ),
    ]
